# -*- coding: utf-8 -*-
"""plant_diseases_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/raushan9217/plant-diseases-detection.6e13ad7f-71a2-4bb0-9c13-b9bcbdaa8c94.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251117/auto/storage/goog4_request%26X-Goog-Date%3D20251117T185106Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Da85c20148b043f24387a5c308d83b83ddb67d5f852328198bc10a51dc02e0af3528a3b5b6ac586c4f4754b673ab75cec099dee6aa386b877dc869e40db351dc227db37aa5e954659264d9aec7707df0b7de33b81b35f43fc75563876484fa58f2a7d09b395264dbd1a5676b0d22facf73b178ad9efcde7c2ccc2493cd5c2d79360b2610104672df24b60f00e84c8a0cd4d1f225619ee3a58bf9f871711eb5a6326110cc64b8692961ebf4eb05ddd01a31930238e0b972a2515cdc8b5bdf38fa425e1956900ac55f3dab31fceb2de42188e99a1f545825b4ef0e91ecc716c3b9ef428ed8496301f09c9f7f6fa3ae06e2acb1be55aa4c4caf04ce58b8a5e200d41
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
vipoooool_new_plant_diseases_dataset_path = kagglehub.dataset_download('vipoooool/new-plant-diseases-dataset')

print('Data source import complete.')

"""# **Import Libraries:**"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Dropout,MaxPooling2D,Flatten
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint
import matplotlib.pyplot as plt
import numpy as np

"""# **Read Dataset:**

## Read Training Data
"""

train_data=ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

train_generator=train_data.flow_from_directory(
    '/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train/',
    target_size=(150, 150),
    batch_size=128,
    class_mode='categorical',
    subset='training'  # Set to 'training' for training images

)

"""## Read Validation Data"""

validation_generator = train_data.flow_from_directory(
    '/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train/',
    target_size=(150, 150),
    batch_size=128,
    class_mode='categorical',
    subset='validation'  # Set to 'validation' for validation images
)

"""## Read Test Data"""

test_data=ImageDataGenerator(
    rescale=1./255
)

test_generator=test_data.flow_from_directory(
    '/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid/',
    target_size=(150, 150),
    batch_size=128,
    class_mode='categorical'

)

"""# **Showing Each Class Name and Coressponding Index:**"""

# Display the 38 unique class names (labels) each one in seperated line
for label,index in train_generator.class_indices.items():
    print(index," : ",label)

# Get a batch of images and labels from the train_generator
images, labels = next(train_generator)  # Get the next batch (128 images in this case)

# Reverse the class_indices dictionary to get a mapping from index to class name
class_labels = {v: k for k, v in train_generator.class_indices.items()}

# Convert one-hot encoded labels back to the index form (if using categorical mode)
label_indices = np.argmax(labels, axis=1)

# If you want to shuffle the batch and display 50 random images
random_indices = np.random.choice(len(images), 50, replace=False)  # Choose 50 random indices

# Plot 50 random images with labels
plt.figure(figsize=(20, 20))
for i, idx in enumerate(random_indices):
    plt.subplot(10, 5, i + 1)  # Create a grid of 5 rows and 10 columns
    plt.imshow(images[idx])
    plt.title(class_labels[label_indices[idx]])  # Show the label as the title
    plt.axis('off')  # Hide the axis

plt.show()

"""# **CNN Model:**"""

model=Sequential([
  # Input Layer in CNN
  Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)),



  # Feture Extraction Layers in CNN with MaxPooling
  Conv2D(32,(3,3),activation='relu'),
  MaxPooling2D((2,2)),
  Conv2D(64,(3,3),activation='relu'),
  MaxPooling2D((2,2)),
  Conv2D(128,(3,3),activation='relu'),
  MaxPooling2D((2,2)),
  Conv2D(256,(3,3),activation='relu'),
  MaxPooling2D((2,2)),
  Conv2D(512,(3,3),activation='relu'),
  MaxPooling2D((2,2)),


# Fully Connected Neural Network
  Flatten(),
  Dense(512, activation='relu'),
  Dropout(0.5),
  Dense(38, activation='softmax')  # 38 classes

])

model.summary()

"""# **Plotting CNN Model:**"""

from tensorflow.keras.utils import plot_model
plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

"""# **Fitting the CNN Model:**"""

from tensorflow.keras import metrics
model.compile(optimizer='adam',loss='categorical_crossentropy'
              ,metrics=['accuracy',metrics.Recall(),metrics.Precision()])

early_stopping=EarlyStopping(monitor='val_loss',patience=5)
model_checkpoint=ModelCheckpoint(
    'best_model.keras',  # File path where the model will be saved
    monitor='val_loss',  # Metric to monitor
    save_best_only=True,  # Save only the model with the best validation loss
    mode='min',  # 'min' because lower loss is better
    verbose=1  # Verbosity mode
)

history=model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // train_generator.batch_size,
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // validation_generator.batch_size,
    epochs=50,
    callbacks=[early_stopping,model_checkpoint],
    verbose=1
)

"""# **Showing Training and Validation Accuracy of Best Model after Finishing Training Epochs**"""

# using max to use best model saved by modelcheckpoint
train_accuracy = max(history.history['accuracy'])
val_accuracy = max(history.history['val_accuracy'])

print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Validation Accuracy: {val_accuracy:.4f}")

"""# **Model Evaluation:**"""

results = model.evaluate(test_generator)
loss = results[0]
accuracy = results[1]
precision = results[2]
recall = results[3]

print(f'Testing Loss: {loss}')
print(f'Testing Accuracy: {accuracy}')
print(f'Testing Precision: {precision}')
print(f'Testing Recall: {recall}')

"""# **Visualization of CNN Model Evaluation Metrics:**"""

import matplotlib.pyplot as plt

# Create a figure with 1 row and 2 columns for subplots
fig, axs = plt.subplots(1, 2, figsize=(14, 5))

# Plot training and validation accuracy
axs[0].plot(history.history['accuracy'], label='Training Accuracy')
axs[0].plot(history.history['val_accuracy'], label='Validation Accuracy')
axs[0].set_xlabel('Epochs')
axs[0].set_ylabel('Accuracy')
axs[0].set_title('Training and Validation Accuracy')
axs[0].legend()

# Plot training and validation loss
axs[1].plot(history.history['loss'], label='Training Loss')
axs[1].plot(history.history['val_loss'], label='Validation Loss')
axs[1].set_xlabel('Epochs')
axs[1].set_ylabel('Loss')
axs[1].set_title('Training and Validation Loss')
axs[1].legend()

# Adjust layout to prevent overlap
plt.tight_layout()
plt.show()

# Get predictions on the validation set
y_probs = model.predict(validation_generator)   # probabilities for each class
y_pred = np.argmax(y_probs, axis=1)             # pick highest probability class

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Step 1: Get predictions
y_probs = model.predict(validation_generator)   # probabilities
y_pred = np.argmax(y_probs, axis=1)             # predicted labels
y_true = validation_generator.classes           # true labels

# Step 2: Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
labels = list(validation_generator.class_indices.keys())

plt.figure(figsize=(12, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

# Step 3: Classification Report
print("Classification Report:\n")
print(classification_report(y_true, y_pred, target_names=labels))

"""# **Evaluation Function For all Train,Valid and Test**"""

def Evaluate_model(model, train_generator, validation_generator, test_generator):
    model_evaluate_train = model.evaluate(train_generator)
    print("Loss       : ", model_evaluate_train[0])
    print("Accuracy   : ", model_evaluate_train[1])
    print("Precision  : ", model_evaluate_train[2])
    print("Recall     : ", model_evaluate_train[3])


    model_evaluate_valid = model.evaluate(validation_generator)
    print("Loss       : ", model_evaluate_valid[0])
    print("Accuracy   : ", model_evaluate_valid[1])
    print("Precision  : ", model_evaluate_valid[2])
    print("Recall     : ", model_evaluate_valid[3])


    model_evaluate_test = model.evaluate(test_generator)
    print("Loss       : ", model_evaluate_test[0])
    print("Accuracy   : ", model_evaluate_test[1])
    print("Precision  : ", model_evaluate_test[2])
    print("Recall     : ", model_evaluate_test[3])

    return np.round(model_evaluate_train[0], 2), np.round(model_evaluate_test[0], 2), \
           np.round(model_evaluate_train[1], 2), np.round(model_evaluate_test[1], 2), \
           np.round(model_evaluate_train[2], 2), np.round(model_evaluate_test[2], 2), \
           np.round(model_evaluate_train[3], 2), np.round(model_evaluate_test[3], 2)

"""# **Print all Evaluation Metrics of both Train,Valid,Testing**"""

Final_Report = []

Final_Report.append(Evaluate_model(model, train_generator, validation_generator, test_generator))

"""# **Save the Model:**"""

model.save('/kaggle/working/my_cnn_model.h5')